config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'

  get 'reviews/new'

  get 'reviews/create'

  get 'reviews/show'

  get 'reviews/edit'

  get 'reviews/update'

  get 'reviews/destroy'

  get 'restaurants/index'

  get 'restaurants/create'

  get 'restaurants/new'

  get 'restaurants/edit'

  get 'restaurants/update'

  get 'restaurants/show'

  get 'restaurants/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :index, :new, :create ]
  end
  resources :reviews, only: [ :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy #if restaurant deleted, so is the reviews
  validates :phone_number, presence: true
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ['chinese','italian','japanese','french','belgian'], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false}, numericality: { only_integer: true }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save #if does not go through validations, save is false
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    #done
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def show
    #done
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name,:phone_number,:address,:category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)

    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_review
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control'%>
  <br>
  <%= f.label :category %>
  <%= f.select :category, %w(japanese chinese belgian french italian), {}, class: 'form-control' %>
  <br>
  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>
  <br>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number, class: 'form-control'%>
  <br>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurant Edit</h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Restaurants <span class="sr-only">(current)</span></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<style>
div.container {
    width: 80%;
    border: 1px solid gray;
    text-align: center;
}
</style>
<div class="container">
<h1>**** RESTAURANTS ****</h1>
<%= link_to 'New Restaurant', new_restaurant_path, class: "btn btn-success" %>
<% @restaurants.each do |restaurant| %>
  <h2> <%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
  <p>Catergory: <%= restaurant.category %></p>
  <p>Address: <%= restaurant.address %></p>
  <p>Phone Number: <%= restaurant.phone_number %></p>
  <p><%=link_to "New Review", new_restaurant_review_path(restaurant), class: "btn btn-primary" %> </p>
  <hr>
<% end %>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1>Restaurant Show</h1>

<h2><%= @restaurant.name %></h2>
<p>Catergory: <%= @restaurant.category %></p>
<p>Address: <%= @restaurant.address %></p>
<p>Phone Number: <%= @restaurant.phone_number %></p>
<p><%= link_to "All Restaurants", restaurants_path %></p>
<p><%= link_to "Edit restaurant", edit_restaurant_path(@restaurant) %></p>
<p><%= link_to "Delete", restaurant_path(@restaurant),
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>
<br>
<h3>Reviews:</h3>
<p><% @restaurant.reviews.each do |x| %> </p>
   <p> <%= x.content %> <%= x.rating  %> </p>
   <% end %>

<%=link_to "Add a review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.label :rating %>
  <%= f.text_field :rating, class: 'form-control'%>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control'%>
  <br>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>